# This is the mods.toml file for Forge mods.
# TOML spec v0.5.0

modLoader = "javafml" # mandatory
loaderVersion = "${loader_version_range}" # mandatory, matches Forge major version range
license = "${mod_license}" # mandatory

# Optional metadata
# issueTrackerURL = ""

[[mods]] # mandatory - defines one mod
modId = "${mod_id}" # must match @Mod value
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''
${mod_description}
'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"